clean: true

theme: fullwidth

output: docs
source_directory: Sources
readme: README.md

module: RouteDocs
undocumented_text: ""
github_url: https://github.com/sersoft-gmbh/route-docs

author: ser.soft GmbH
author_url: https://sersoft.de
