name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-spm:
    strategy:
      matrix:
        os: [ macos-12 ]
        swift-version: [ '' ]
        xcode-version: [ '^14.1' ]
        include:
          - os: ubuntu-20.04
            swift-version: 5.7
            xcode-version: ''
          - os: ubuntu-22.04
            swift-version: 5.7
            xcode-version: ''

    runs-on: ${{ matrix.os }}

    steps:
      - if: ${{ runner.os == 'macOS' }}
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Install Swift
        if: ${{ runner.os == 'Linux' }}
        uses: sersoft-gmbh/swifty-linux-action@v2.1.1
        with:
          release-version: ${{ matrix.swift-version }}
          platform: ${{ matrix.os }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Read OS Version
        uses: sersoft-gmbh/os-version-action@v2.0.0
        id: os-version
      - name: Read Swift Version
        uses: sersoft-gmbh/swift-version-action@v2.0.1
        id: swift-version
      - uses: actions/checkout@v3.1.0
      - uses: actions/cache@v3.0.11
        with:
          path: .build
          key: ${{ runner.os }}-${{ steps.os-version.outputs.version }}-spm-${{ steps.swift-version.outputs.version }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.os-version.outputs.version }}-spm-${{ steps.swift-version.outputs.version }}-
      - name: Build & Test
        run: swift test -v --parallel --enable-code-coverage
      - name: Generate Coverage Files
        uses: sersoft-gmbh/swift-coverage-action@v3.0.0
        id: coverage-files
      - uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ join(fromJSON(steps.coverage-files.outputs.files), ',') }}
          fail_ci_if_error: true

  test-xcode:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: ^14.1
      - name: Read OS Version
        uses: sersoft-gmbh/os-version-action@v2.0.1
        id: os-version
      - name: Read Swift Version
        uses: sersoft-gmbh/swift-version-action@v2.0.1
        id: swift-version
      - uses: actions/checkout@v3.1.0
      - uses: actions/cache@v3.0.11
        with:
          path: .derived-data
          key: ${{ runner.os }}-${{ steps.os-version.outputs.version }}-xcode-${{ steps.swift-version.outputs.version }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.os-version.outputs.version }}-xcode-${{ steps.swift-version.outputs.version }}-
      # The `dump-pif` is a workaround for the PIF generation failure.
      # Since this resolves the packages, we also cache this.
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-${{ steps.os-version.outputs.version }}-spm-${{ steps.swift-version.outputs.version }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.os-version.outputs.version }}-spm-${{ steps.swift-version.outputs.version }}-
      - run: swift package dump-pif > /dev/null
      - uses: sersoft-gmbh/xcodebuild-action@v2.0.1
        timeout-minutes: 15
        with:
          spm-package: './'
          scheme: route-docs
          destination: platform=macOS
          action: test
          parallel-testing-enabled: true
          enable-code-coverage: true
          derived-data-path: .derived-data
      - uses: sersoft-gmbh/swift-coverage-action@v3.0.1
        id: coverage-files
      - uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ join(fromJSON(steps.coverage-files.outputs.files), ',') }}
          fail_ci_if_error: true
