#if !canImport(ObjectiveC)
import XCTest

extension DocumentationDecoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DocumentationDecoderTests = [
        ("testDocObject", testDocObject),
        ("testPassingCustomUserInfo", testPassingCustomUserInfo),
        ("testSimpleStruct", testSimpleStruct),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DocumentationDecoderTests.__allTests__DocumentationDecoderTests),
    ]
}
#endif
