#if !canImport(ObjectiveC)
import XCTest

extension RouteDocsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RouteDocsTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RouteDocsTests.__allTests__RouteDocsTests),
    ]
}
#endif
